/**
 * Generated-file markers.
 *
 * Every exported file gets a short header naming its source and a fingerprint of the generated
 * content. Later, `inspectFile` can tell whether a file on disk (or in a Shopify theme) is still
 * exactly what SectionForge produced, or has been edited by hand — so a re-export won't silently
 * overwrite someone's changes.
 */

export type FileKind = 'html' | 'css' | 'liquid';

const TAG = 'sectionforge-hash:';
const normalize = (s: string) =>
  s
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((l) => l.trimEnd())
    .join('\n')
    .trim();

/** FNV-1a, 32-bit — tiny and plenty for change detection (not security). */
export function fingerprint(s: string): string {
  let h = 0x811c9dc5;
  const t = normalize(s);
  for (let i = 0; i < t.length; i++) {
    h ^= t.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}

function header(kind: FileKind, source: string, hash: string): string {
  const lines = [
    `Generated by SectionForge from ${source}.`,
    'Edit the design in SectionForge and re-export — hand edits here will be overwritten.',
    `${TAG}${hash}`,
  ];
  if (kind === 'css') return `/*\n * ${lines.join('\n * ')}\n */\n`;
  if (kind === 'liquid') return `{%- comment -%}\n  ${lines.join('\n  ')}\n{%- endcomment -%}\n`;
  return `<!--\n  ${lines.join('\n  ')}\n-->\n`;
}

/** Strip a SectionForge header block (any kind) from the start of a file. */
function stripHeader(text: string): string {
  const t = text.replace(/\r\n?/g, '\n');
  const patterns = [
    /^(<!DOCTYPE[^>]*>\n)?<!--\n[\s\S]*?sectionforge-hash:[0-9a-f]{8}\n-->\n/i,
    /^\/\*\n[\s\S]*?sectionforge-hash:[0-9a-f]{8}\n \*\/\n/,
    /^\{%-? comment -?%\}\n[\s\S]*?sectionforge-hash:[0-9a-f]{8}\n\{%-? endcomment -?%\}\n/,
  ];
  for (const re of patterns) {
    const m = re.exec(t);
    if (m) return (m[1] ?? '') + t.slice(m[0].length);
  }
  return t;
}

export function withMarker(code: string, kind: FileKind, source: string): string {
  const hash = fingerprint(code);
  const h = header(kind, source, hash);
  // keep <!DOCTYPE> first so the page stays in standards mode
  const doctype = /^<!DOCTYPE[^>]*>\n/i.exec(code);
  return doctype ? doctype[0] + h + code.slice(doctype[0].length) : h + code;
}

export interface FileCheck {
  status: 'unmarked' | 'unchanged' | 'edited';
  /** lines that differ from what the current design would export */
  vsCurrent: number;
}

/** Rough line-level difference count (multiset symmetric difference, halved). */
function lineDiff(a: string, b: string): number {
  const count = new Map<string, number>();
  for (const l of normalize(a).split('\n')) count.set(l, (count.get(l) ?? 0) + 1);
  let extra = 0;
  for (const l of normalize(b).split('\n')) {
    const c = count.get(l) ?? 0;
    if (c > 0) count.set(l, c - 1);
    else extra++;
  }
  let missing = 0;
  for (const c of count.values()) missing += c;
  return Math.max(extra, missing);
}

export function inspectFile(text: string, currentCode: string): FileCheck {
  const m = new RegExp(`${TAG}([0-9a-f]{8})`).exec(text);
  const body = stripHeader(text);
  const vsCurrent = lineDiff(body, currentCode);
  if (!m) return { status: 'unmarked', vsCurrent };
  return { status: fingerprint(body) === m[1] ? 'unchanged' : 'edited', vsCurrent };
}
